# Sonali,BCA ADC
from tkinter import *
note=Tk()
menu=Menu(note)
note.config(menu=menu)
file=Menu(menu)
menu.add_cascade(label='File',menu=file)
file.add_command(label='New')
file.add_command(label='Open...')
file.add_command(label='Save')
file.add_command(label='Save As...')
file.add_command(label='Page Setup...')
file.add_command(label='Print')
file.add_command(label='Exit',command=quit)
edit=Menu(menu)
menu.add_cascade(label='Edit',menu=edit)
edit.add_command(label='Undo')          
edit.add_command(label='Cut')
edit.add_command(label='Copy')
edit.add_command(label='Paste')
edit.add_command(label='Delete')
edit.add_command(label='Find')
edit.add_command(label='Find Next')
edit.add_command(label='Replace...')
edit.add_command(label='Go To...')
edit.add_command(label='Select All')
edit.add_command(label='Time/Date')
format=Menu(menu)
menu.add_cascade(label='Format',menu=format)
format.add_command(label='Word Wrap')
format.add_command(label='Font...')
view=Menu(menu)
menu.add_cascade(label='View',menu=view)
view.add_command(label='Status Bar')
help=Menu(menu)
menu.add_cascade(label='Help',menu=help)
help.add_command(label='View Help')
help.add_command(label='About Notepad')
mainloop()